name: Deploy ZetaSlate (pull + restart IIS)

on:
  push:
    branches: [ main ]

concurrency:
  group: zetaslate-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  SITE_PATH: 'C:\\inetpub\\wwwroot\\zetaslate'   # folder IIS serves
  WARMUP_URL: 'https://zetaslate.com/'

jobs:
  deploy:
    runs-on: [ self-hosted, windows, x64 ]

    defaults:
      run:
        shell: powershell

    steps:
    # 0 ── bring the repo into the workspace so subsequent steps can see it
    - uses: actions/checkout@v4

    # 1 ── make the on-disk site copy pull-able without prompting
    - name: Configure Git for non-interactive fetch
      run: |
        git config --global --add safe.directory $Env:SITE_PATH
        $token = '${{ secrets.GITHUB_TOKEN }}'
        $url   = "https://x-access-token:$token@github.com/AB-Coder96/zetaslate.git"
        git -C $Env:SITE_PATH remote set-url origin $url

    # 2 ── fast-forward the IIS-served working tree to main
    - name: Pull latest commit into SITE_PATH
      run: |
        git -C $Env:SITE_PATH fetch --all --prune
        git -C $Env:SITE_PATH reset --hard origin/main

    # 3 ── install Python + pip cache (cache hash uses workspace/requirements.txt)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'   # now resolvable

    # 4 ── install/update all Python deps
    - name: Install backend requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r "${{ github.workspace }}\\requirements.txt"

    # 5 ── restart IIS so new code + deps are loaded
    - name: Restart IIS
      run: |
        iisreset /stop
        iisreset /start

    # 6 ── warm-up request so first user hit is fast
    - name: Warm-up request
      run: |
        Invoke-WebRequest -Uri $Env:WARMUP_URL -UseBasicParsing -TimeoutSec 30
