name: Auto-pull to server

on:
  push:                 # run on every push to the default branch
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Allow repo path for Git
      shell: powershell
      run: git config --global --add safe.directory 'C:/inetpub/wwwroot/zetaslate'

    - name: Fast-forward production copy
      shell: powershell
      run: |
        cd 'C:\inetpub\wwwroot\zetaslate'
        git fetch --all
        git reset --hard origin/main
