name: Auto-pull to IIS web-root

on:
  push:
    branches: [ main ]      # adjust if you deploy a different branch

jobs:
  deploy:
    runs-on: [ self-hosted, windows, x64 ]

    steps:
    # 1 ── mark the path safe (avoids "dubious ownership")
    - name: Allow IIS folder for Git
      shell: powershell
      run: git config --global --add safe.directory 'C:/inetpub/wwwroot/zetaslate'

    # 2 ── FIX: point 'origin' at a sane, tokenised URL *without* the extra slash
    - name: Fix origin URL for token auth
      shell: powershell
      run: |
        $token = '${{ secrets.GITHUB_TOKEN }}'
        $url   = "https://x-access-token:$token@github.com/AB-Coder96/zetaslate.git"
        git -C 'C:\inetpub\wwwroot\zetaslate' remote set-url origin $url
        git -C 'C:\inetpub\wwwroot\zetaslate' remote -v           # show for debug

    # 3 ── pull the latest commit
    - name: Fast-forward production copy
      shell: powershell
      run: |
        cd 'C:\inetpub\wwwroot\zetaslate'
        git fetch --all --prune
        git reset --hard origin/main

    # 4 ── (optional) recycle the IIS app-pool so the site reloads instantly
    # - name: Recycle default app-pool
    #   shell: powershell
    #   run: Restart-WebAppPool 'DefaultAppPool'
