name: Deploy ZetaSlate (pull + restart IIS)

on:
  push:
    branches: [ main ]

concurrency:
  group: zetaslate-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  # ————————————————————————————————————————————————————————————————
  # Path where IIS serves the repo  (already cloned on the runner)
  SITE_PATH: 'C:\\inetpub\\wwwroot\\zetaslate'
  # Used to warm-up Django after the restart
  WARMUP_URL: 'https://zetaslate.com/'

jobs:
  deploy:
    runs-on: [ self-hosted, windows, x64 ]

    defaults:
      run:
        shell: powershell

    steps:
    # 1 ───────────────────────────────────────────────────────────────
    # Tell GitHub runner that this path is safe and patch the remote URL
    - name: Configure Git for non-interactive fetch
      run: |
        git config --global --add safe.directory $Env:SITE_PATH
        $token = '${{ secrets.GITHUB_TOKEN }}'
        $url   = "https://x-access-token:$token@github.com/AB-Coder96/zetaslate.git"
        git -C $Env:SITE_PATH remote set-url origin $url

    # 2 ───────────────────────────────────────────────────────────────
    # Fast-forward the working copy to the newest commit
    - name: Pull latest commit
      run: |
        git -C $Env:SITE_PATH fetch --all --prune
        git -C $Env:SITE_PATH reset --hard origin/main

    # 3 ───────────────────────────────────────────────────────────────
    # Install Python + pip cache (points at real requirements.txt)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        # ↓↓↓ exact file so the cache hash can be built
        cache-dependency-path: '${{ env.SITE_PATH }}\\backend\\requirements.txt'

    # 4 ───────────────────────────────────────────────────────────────
    # Install / update all backend dependencies
    - name: Install backend requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r "$Env:SITE_PATH\\backend\\requirements.txt"

    # 5 ───────────────────────────────────────────────────────────────
    # Restart IIS so the new code and packages are picked up
    - name: Restart IIS
      run: |
        iisreset /stop
        iisreset /start

    # 6 ───────────────────────────────────────────────────────────────
    # First request warms up Django + caches templates
    - name: Warm-up request
      run: |
        Invoke-WebRequest -Uri $Env:WARMUP_URL -UseBasicParsing -TimeoutSec 30
