name: Deploy Site (pull + restart IIS + ensure Postgres)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: site-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  SITE_PATH: 'C:\\inetpub\\wwwroot\\zetaslate'    # IIS site folder

jobs:
  deploy:
    runs-on: [ self-hosted, windows, x64 ]
    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v4

    # 0½ ── derive host & export env-vars (PowerShell-5 safe)
    - name: Load project config
      run: |
        $cfgPath = "${{ github.workspace }}\project-config.json"
        $cfg     = @{}
        if (Test-Path $cfgPath) {
          $cfg = Get-Content -Raw $cfgPath | ConvertFrom-Json
        }

        $siteName = Split-Path -Leaf $Env:SITE_PATH

        $domain = '.com'
        if ($cfg -ne $null -and $cfg.PSObject.Properties['websitedomain']) {
          if ($cfg.websitedomain) { $domain = $cfg.websitedomain }
        }

        $host = "$siteName$domain"
        "WARMUP_URL=https://$host/"                | Out-File $Env:GITHUB_ENV -Append
        "DJANGO_ALLOWED_HOSTS=$host,www.$host"     | Out-File $Env:GITHUB_ENV -Append
        "SITE_NAME=$siteName"                      | Out-File $Env:GITHUB_ENV -Append

    # 1 ── configure Git for IIS tree
    - name: Configure Git
      run: |
        git config --global --add safe.directory $Env:SITE_PATH
        $url = "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git -C $Env:SITE_PATH remote set-url origin $url

    - name: Set global Git identity
      run: |
        git config --global user.name  "${{ github.actor }} (GitHub Actions)"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Pull site code
      run: |
        git -C $Env:SITE_PATH fetch --all --prune
        git -C $Env:SITE_PATH reset --hard origin/main

    # 2 ── Python setup & install deps
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: 'backend/requirements.txt'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r "${{ github.workspace }}\backend\requirements.txt"

    # 3 ── restart IIS
    - name: Restart IIS
      run: |
        iisreset /stop
        iisreset /start

    # 4 ── ensure PostgreSQL cluster / service (unchanged)
    - name: Ensure & (re)start PostgreSQL
      run: |
        $svc = Get-WmiObject Win32_Service | ? { $_.Name -like 'postgresql*' } |
               Sort-Object Name -Descending | Select-Object -First 1
        if (-not $svc) { throw 'PostgreSQL service not found' }

        $cmd = $svc.PathName
        if ($cmd -match '"([^"]+\\pg_ctl\.exe)"')      { $pgCtl = $Matches[1] }
        elseif ($cmd -match '([^\s"]+\\pg_ctl\.exe)')  { $pgCtl = $Matches[1] }
        else { throw 'pg_ctl.exe not found' }

        if ($cmd -match '-D\s+"([^"]+)"')      { $data = $Matches[1] }
        elseif ($cmd -match '-D\s+([^\s"]+)')  { $data = $Matches[1] }
        else { throw 'data dir not found' }

        if (-not (Test-Path $data)) {
          & "$pgCtl" initdb -D "$data"
          & "$pgCtl" register -N $svc.Name -D "$data" -U 'NT AUTHORITY\NetworkService'
          Set-Service $svc.Name -StartupType Automatic
          Start-Service $svc.Name
        } else {
          Restart-Service $svc.Name -Force
        }

    # 4½ ── ensure role & DB once (unchanged, PowerShell-5 safe)
    - name: Ensure DB & role exist
      run: |
        $Env:PGPASSWORD = $Env:POSTGRES_PASSWORD
        echo "::add-mask::$Env:PGPASSWORD"

        if ($Env:POSTGRES_DB)   { $db   = $Env:POSTGRES_DB }   else { $db   = $Env:SITE_NAME }
        if ($Env:POSTGRES_USER) { $user = $Env:POSTGRES_USER } else { $user = $Env:SITE_NAME }

        $sup  = $Env:POSTGRES_SUPERUSER
        $svc  = Get-WmiObject Win32_Service | ? { $_.Name -like 'postgresql*' } |
                Sort-Object Name -Descending | Select-Object -First 1
        $bin  = ''
        if ($svc.PathName -match '"([^"]+\\)pg_ctl\.exe"')      { $bin = $Matches[1] }
        elseif ($svc.PathName -match '([^\s"]+\\)pg_ctl\.exe')  { $bin = $Matches[1] }

        $psql = ($bin) ? ($bin + 'psql.exe') : 'psql'
        if (-not (Test-Path $psql)) { $psql = 'psql' }

        $roleExists = & "$psql" -U $sup -tAc "SELECT 1 FROM pg_roles WHERE rolname='$user'"
        if (-not $roleExists) {
          & "$psql" -U $sup -c "CREATE USER $user WITH PASSWORD '$Env:POSTGRES_PASSWORD';"
        }

        $dbExists = & "$psql" -U $sup -tAc "SELECT 1 FROM pg_database WHERE datname='$db'"
        if (-not $dbExists) {
          & "$psql" -U $sup -c "CREATE DATABASE $db OWNER $user;"
        }

    # 5 ── Django migrate
    - name: Django migrate
      run: |
        $proj = Join-Path $Env:SITE_PATH 'backend'
        if (-not (Test-Path "$proj\manage.py")) { throw "manage.py not found at $proj" }
        Set-Location $proj
        python manage.py migrate --noinput

    # 6 ── warm-up
    - name: Warm-up request
      run: |
        Invoke-WebRequest -Uri $Env:WARMUP_URL -UseBasicParsing -TimeoutSec 30
